### PR TITLE
Typescript debugging with Chrome

### PR DESCRIPTION
**Pull request by helenli8181**
### List of Changes:

- Added new launch configuration that allows client-side debugging with Chrome

### Notes:

- To use this, first install the [Debugger for Chrome extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) in VS Code. Go to the Run menu and run "Launch Chrome against localhost" as the config. You should be able to add breakpoints in the VS Code editor.
- Another option for frontend debugging in the Chrome browser is to go to "Inspect" -> "Sources" -> "Page" -> whatever .ts file you want to debug. You can add breakpoints there and refresh, but this doesn't have the benefit of being able to save the code you edit. 

### Steps:

1. Install [Debugger for Chrome extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) in VS Code.
2. Open Visual Studio in the `Main` folder, such that `.vscode` is a direct access file (see image) instead of within any other folders. 
    - .vscode Direct Access File
3. Go to the Run menu.
4. Go to the Terminal (make a new Terminal with Terminal -> New Terminal).
5. Label port 3000 as a debugging port. See [the README](https://github.com/microsoft/vscode-chrome-debug). If you are on macOS for example, the command is `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=3000`.
6. Set a breakpoint somewhere in the `frontend` folder that will be reached by the codebase.
7. In the terminal, run `cd frontend` and then `npm start`. (The terminal type may be `node` at this point.)
8. Once that finishes running (and `localhost:3000` is opened), go to the Run tab on the left, find `Launch Chrome against Localhost`, and click the green "Go" arrow to run this. A new Chrome window should open.
9. Navigate to whatever page will trigger the breakpoint; once you have done this, you should see the variables at that stage under "Variables".
10. Use this to debug the frontend!

### CODE REVIEW

**Comment by zpChris** [comment]
You didn't request me but it seems like this PR is finished, so I added myself and to review it.

**Comment by zpChris** [comment]
I don't think I have the same Visual Studio Code setup as indicated by this extension, so I'll wait for the daily sync to talk about this PR.

**Comment by helenli8181** [comment]
> I don't think I have the same Visual Studio Code setup as indicated by this extension, so I'll wait for the daily sync to talk about this PR.

I think I misspoke; All the Debugging stuff is under the Run menu on the left of VS Code. After pulling this launch.json file you should see the Launch Chrome against localhost configuration there.

**Comment by zpChris** [comment]
> I think I misspoke; All the Debugging stuff is under the Run menu on the left of VS Code. After pulling this launch.json file you should see the Launch Chrome against localhost configuration there.

I still don't see this -- maybe you can show me during the standup?

**Comment by alankbi** [comment]
I don't use VSCode so this PR may not be relevant to me haha - I'll go ahead and remove myself as a reviewer. If you still want 2 approvals on this before merging tho lmk and I can quickly approve it as well (but since it's a smaller one I figure 1 approval might be good enough)

**Review by zpChris — APPROVED** [review]
LGTM! I added the steps I had to go through (thanks @helenli8181 for the help with this!) in the description.

**Review by alankbi — APPROVED** [review]

**Pull request merged**
