### PR TITLE
Add difficulty to problem classes and endpoints

### PR DESCRIPTION
**Pull request by alankbi**
### List of Changes:

* Add difficulty to problem class and REST endpoints
* Create and update associated tests
* Move `BAD_SETTING` error from `RoomErrors` to `ProblemErrors`

### Notes:

* It's a bit awkward cause right now the difficulty enum is shared between the room selection and problem creation processes, so while random makes sense for the first one, it is less so for the second one. As of now I have it throw a bad setting error if that happens, but I'm open to changing that, just lmk

### Screencast and Images:

Create a problem: 
Create problem POST request

Problem database table: 
Problem database table

### CODE REVIEW

**Comment by alankbi** [comment]
Actually, I have this merging into #69, so I removed y'all as reviewers until that one is merged in first

**Comment by zpChris** [comment]
[Add problem difficulty field to create problem endpoint](https://trello.com/c/RgrBKcyQ/179-add-problem-difficulty-field-to-create-problem-endpoint)

**Review by zpChris — APPROVED** [review]
LGTM! No notes or changes 👍

**Review by helenli8181 — APPROVED** [review]
This looks good to me! No objections.

**Pull request merged**
