### PR TITLE
Update scripts to use react-app-rewired while maintaining quick build speed.

### PR DESCRIPTION
**Pull request by zpChris**
### List of Changes:
- Update scripts to use `react-app-rewired` on start, build, and test.

### Notes:
- This change was originally made in PR #62. Attached to that is a link that explains the [config file changes](https://github.com/react-monaco-editor/react-monaco-editor#usage-with-create-react-app) and the [usage of react-app-rewired](https://github.com/timarney/react-app-rewired).
- I believe this runs faster because I changed the `"test"` script to use `react-app-rewired` as well, whereas before in PR #62 only the `"start"` and `"build"` scripts were updated. However, we'll see if this works on merge and deploy.

### Screencast and Images:
No images or screencasts are used in this PR.

### CODE REVIEW

**Comment by zpChris** [comment]
[Update workflow.yml and npm build to maintain test speed but deploy full syntax highlighting](https://trello.com/c/81qEWOPl/187-update-workflowyml-and-npm-build-to-maintain-test-speed-but-deploy-full-syntax-highlighting)

**Review by alankbi — APPROVED** [review]
Approved, however before merging this could we rerun the tests a few times to see if it works 100% of the time? I remember with the original PR the tests would pass like half the time (both when just `start` and `build` were updated to `react-app-rewired` and when all four scripts were updated)

**Review by helenli8181 — APPROVED** [review]
Approved!

**Comment by zpChris** [comment]
The first merge attempt failed citing a failed socket test, even though I tested three times prior -- running again.

**Comment by zpChris** [comment]
Merging this pull request has failed 4-5 times, so I'll stop now and discuss during the standup.

**Pull request merged**
